create table applications(
    id integer primary key,
    chat_id integer not null,
    telegram_id varchar(255) not null,
    appl_type integer null,
    subscription_checked boolean default false,
    country varchar(255) null,
    mark_or_conditions varchar(255) null,
    budget varchar(255) null,
    steering_wheel_type varchar(255) null,
    city varchar(255) null,
    agent_fio varchar(255) null,
    agent_phone varchar(255) null,
    person_name varchar(255) null,
    email varchar(255) null,
    person_phone varchar(255) null,
    step varchar(255) not null default "coop_type",
    mark varchar(255) null,
    model varchar(255) null,
    car_year varchar(255) null,
    additional_info text null,
    created_at text not null,
    updated_at text not null,
    sended_telegram boolean default false,
    sended_bitrix boolean default false
);